# This is a basic workflow to help you get started with Actions

name: ContinuousIntegration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" candidatos
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: "19"
          distribution: "temurin"
          cache: maven
      # Candidatos
      - name: Run test suite candidatos
        working-directory: candidatos
        run: |
          mvn test
      
      - name: Add coverage to PR candidatos
        id: jacoco-candidatos
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/candidatos/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      # Empresas
      - name: Run test suite empresas
        working-directory: empresas
        run: |
          mvn test
      
      - name: Add coverage to PR empresas
        id: jacoco-empresas
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/empresas/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
